### PR TITLE
Allow processing of large batches in smaller subbatches to save memory

### PR DESCRIPTION
**Pull request by rgemulla**
This generalizes the chunking functionality that was previously present in the negative sampling trainer to all trainers.

### CODE REVIEW

**Review by AdrianKs — APPROVED** [review]
Looks good. I adapted the naming in the comments in negative sampling from chunks to subbatches.

The numbers don't change when using subbatches compared to the master branch, so everything seems to be correct.

I think we are ready to merge.

**Comment by rgemulla** [comment]
Did you verify that the numbers stay for all three job types?

**Comment by AdrianKs** [comment]
> Did you verify that the numbers stay for all three job types?

Yes, the numbers stay for all three train-types

**Comment by rgemulla** [comment]
Thanks!

**Pull request merged**
