### PR TITLE
Add CoDEx to list of datasets

### PR DESCRIPTION
**Pull request by tsafavi**
Hi all, I've modified `download_all.sh` and the README to include the relational part of [CoDEx](https://github.com/tsafavi/codex).  I included positive triples `{train,valid,test.txt}` in all three CoDEx datasets, as well as negatives for CoDEx-S and M `{valid_negatives,test_negatives}.txt`. 

However, for the README, I only included the pretrained link prediction models for consistency with the rest of the section, which only mentions the link prediction task. Let me know your thoughts about including/excluding the triple classification results/pretrained models given that LibKGE currently doesn't support TC.

### CODE REVIEW

**Comment by rgemulla** [comment]
Thanks Tara! Would you mind integrating this in the updated master, which now uses revised preprocessing? Should be a rather minor change.

**Comment by tsafavi** [comment]
Minor changes done. However, there's another problem - `data/download_all.sh` calls the `data/preprocess/preprocess_default.py` script, which isn't in the `data/preprocess/` directory. @rgemulla, any chance you have a `preprocess_default.py` file that didn't get pushed with the new changes?

**Comment by rgemulla** [comment]
Indeed, thanks & file added

**Comment by tsafavi** [comment]
Great! My fork should be even with master now.

**Comment by rgemulla** [comment]
Thanks, works great! I shortened the intro somewhat to be in line with the other datasets, let me know if that's fine with you. Ready to merge from my point of view.

**Comment by tsafavi** [comment]
@rgemulla, the description looks good. I just changed the remote locations of the CoDEx datasets from my personal GitHub Pages to Zenodo hosting to make sure I don't ever modify the files accidentally. If that's fine by you then I'm ready to merge as well.

**Comment by rgemulla** [comment]
Thanks @tsafavi!

**Pull request merged**
