### PR TITLE
calculate true scores in evaluation using score_sp and score_po

### PR DESCRIPTION
**Pull request by AdrianKs**
calculate true scores in evaluation with score_sp and score_po to avoid floating point issues influencing tie breaking.
Addresses issue #221

### CODE REVIEW

**Comment by AdrianKs** [comment]
@sfschouten can you please check how this change influences evaluation in your setup. If this still gives unexpected results we may have to calculate true scores with a "special chunk".

**Comment by sfschouten** [comment]
I believe this fixes the problem!
Here's the before and after for a single batch https://rentry.co/rk8o9, https://rentry.co/ue86o.
As you can see the number of ties now seems a lot saner.
To make 100% sure I think I will write some tests next week, but I think this can be merged.

**Comment by rgemulla** [comment]
@AdrianKs Can this be closed?

**Comment by AdrianKs** [comment]
yes, this should be handled with #224 
we can reopen it if needed

**Comment by AdrianKs** [comment]
Considering the issues regarding differences in the outcomes of scoring functions I reopened this PR.
We should use the same implementation for the calculation of true-scores and scores of negatives. This should allow to keep the tie-handling tolerances low.
@rgemulla do you think this is ready to merge?

**Comment by rgemulla** [comment]
Fine with me. You may want to leave the old code in the source code (commented out) for clarity.

**Pull request merged**
