### PR TITLE
Update transe.py

### PR DESCRIPTION
**Pull request by tsafavi**
Missing a return statement in the else clause of the TransE embedding scorer.

### CODE REVIEW

**Comment by rufex2001** [comment]
From a quick look, isn't the "out =" what's missing?

**Comment by tsafavi** [comment]
That would work too, but I was following the standards from other RelationalScorer subclasses, e.g., https://github.com/uma-pi1/kge/blob/a1a8ba04b414e58cc433257da2eddb9bd1e8ba26/kge/model/distmult.py#L24.

**Comment by samuelbroscheit** [comment]
Thanks Tara! Seems a bit inconsistent in our code at the moment. Let's do "out = " to be consistent within the function.

**Comment by samuelbroscheit** [comment]
Thank you!

**Pull request merged**
