### PR TITLE
Update relational_tucker3.yaml

### PR DESCRIPTION
**Pull request by tsafavi**
Update documentation to reflect discussion in https://github.com/uma-pi1/kge/issues/118.

### CODE REVIEW

**Comment by rgemulla** [comment]
Thanks!

**Comment by tsafavi** [comment]
@rgemulla it's worth noting that there is still a default of base_embedder.dim = 100 in `tucker3_relation_embedder.yaml`: https://github.com/tsafavi/kge/blob/5ba82a8bea8514ed13d681b2ed9192b91164c07b/kge/model/embedder/tucker3_relation_embedder.yaml#L7

This default value is not used since it's overwritten by the -1 in `relational_tucker3.yaml`: https://github.com/tsafavi/kge/blob/5ba82a8bea8514ed13d681b2ed9192b91164c07b/kge/model/relational_tucker3.yaml#L17.

**Comment by rgemulla** [comment]
Ahh, I see. I've updated the docs+configuration again and let the model use whatever default is defined in tucker3_relation_embedder.yaml (which is more consistent to what we do everywhere else).

**Comment by samuelbroscheit** [comment]
Thanks @tsafavi ! Yes thats more consistent and now I understand what that issue was about :) .

**Comment by samuelbroscheit** [comment]
Actually the only thing needed in relational_tucker_3.yaml is:

```
  relation_embedder:
    # See tucker3_relation_embedder.yaml for relation embedder options and
    # defaults.
    type: tucker3_relation_embedder
    +++: +++
```

**Comment by rgemulla** [comment]
Yes, but this way it's easier to read/configure.

**Pull request merged**
